# Everything here is available through the `config` dict in the Snakefile

min_date: "2022-07-01"
geo_categories: region
frequency_category: subclade

nextclade_columns:
  - "seqName"
  - "clade"
  - "subclade"
  - "aaSubstitutions"

regions:
  - "Africa"
  - "China"
  - "Europe"
  - "Japan Korea"
  - "North America"
  - "Oceania"
  - "South America"
  - "South Asia"
  - "Southeast Asia"
  - "West Asia"

clades_to_plot:
  h1n1pdm:
    - "C.1"
    - "C.1.1"
    - "C.1.1.1"
    - "C.1.2"
    - "C.1.3"
    - "C.1.5"
    - "C.1.6"
  h3n2:
    - "F.1.1"
    - "G.1.1"
    - "G.1.1.2"
    - "G.1.3"
    - "G.1.3.1"
    - "G.1.3.1.1"
    - "G.1.3.2"
    - "G.2"
    - "G.2.1"
    - "G.2.2"
  vic:
    - "C.1"
    - "C.2"
    - "C.3"
    - "C.4"
    - "C.5"
    - "C.5.1"
    - "C.5.2"
    - "C.5.3"

coloring_field: subclade
auspice_config:
  h1n1pdm: "profiles/flu/auspice_config_h1n1pdm.json"
  h3n2: "profiles/flu/auspice_config_h3n2.json"
  vic: "profiles/flu/auspice_config_vic.json"
