# Everything here is available through the `config` dict in the Snakefile

min_date: "2022-07-01"
geo_categories: region
frequency_category: subclade

nextclade_columns:
  - "seqName"
  - "clade"
  - "subclade"
  - "aaSubstitutions"

regions:
  - "Africa"
  - "China"
  - "Europe"
  - "Japan Korea"
  - "North America"
  - "Oceania"
  - "South America"
  - "South Asia"
  - "Southeast Asia"
  - "West Asia"
