# Everything here is available through the `config` dict in the Snakefile

min_date: "2021-04-01"
geo_categories: region
frequency_category:
  ha: subclade
  na: clade

nextclade_columns:
  ha:
    - "seqName"
    - "clade"
    - "subclade"
    - "aaSubstitutions"
  na:
    - "seqName"
    - "clade"
    - "aaSubstitutions"

regions:
  - "Africa"
  - "China"
  - "Europe"
  - "Japan Korea"
  - "North America"
  - "Oceania"
  - "South America"
  - "South Asia"
  - "Southeast Asia"
  - "West Asia"

clades_to_plot:
  h1n1pdm:
    ha:
      - "C.1"
      - "C.1.1"
      - "C.1.1.1"
      - "C.1.2"
      - "C.1.3"
      - "C.1.5"
      - "C.1.6"
      - "C.1.7"
    na:
      - B.3.1.1
      - C
      - C.2
      - C.3
      - C.4
      - C.5
      - C.5.1.1
      - C.5.2
      - C.5.3
  h3n2:
    ha:
      - "G.1.1.2"
      - "G.1.3.1"
      - "G.1.3.2"
      - "G.2"
      - "G.2.1"
      - "G.2.2"
      - "H"
      - "H.1"
      - "H.2"
      - "H.3"
      - "H.4"
    na:
      - A.2.2.2
      - B.2
      - B.2.2
      - B.3
      - B.4
  vic:
    ha:
      - "C.2"
      - "C.3"
      - "C.5"
      - "C.5.1"
      - "C.5.3"
      - "C.5.4"
      - "C.5.5"
      - "C.5.6"
      - "C.5.7"
    na:
      - B
      - B.3
      - B.5
      - B.7
      - B.7.1
      - B.8

coloring_field: subclade
auspice_config:
  h1n1pdm: "profiles/flu/auspice_config_h1n1pdm.json"
  h3n2: "profiles/flu/auspice_config_h3n2.json"
  vic: "profiles/flu/auspice_config_vic.json"
