# Everything here is available through the `config` dict in the Snakefile

min_date: "2024-05-01"
geo_categories: region
frequency_category:
  ha: proposedSubclade
  na: clade

nextclade_columns:
  ha:
    - "seqName"
    - "clade"
    - "proposedSubclade"
    - "aaSubstitutions"
  na:
    - "seqName"
    - "clade"
    - "aaSubstitutions"

regions:
  - "Africa"
  - "China"
  - "Europe"
  - "Japan Korea"
  - "North America"
  - "Oceania"
  - "South America"
  - "South Asia"
  - "Southeast Asia"
  - "West Asia"

clades_to_plot:
  h1n1pdm:
    ha:
      - C.1.9
      - C.1.9.1
      - C.1.9.2
      - C.1.9.3
      - C.1.9.4
      - D
      - D.1
      - D.5
    na:
      - C.3
      - C.4
      - C.5
      - C.5.2
      - C.5.3
      - C.5.3.1
      - C.5.3.2
      - C.5.3.3
  h3n2:
    ha:
      - J.1.1
      - J.2
      - J.2.1
      - J.2.2
      - J.2.a
      - J.2.b
      - J.2.c
      - J.2.d
      - J.2.e
    na:
      - B.4
      - B.4.1
      - B.4.2
      - B.4.3
  vic:
    ha:
      - C.2
      - C.3
      - C.5
      - C.5.1
      - C.5.4
      - C.5.5
      - C.5.6
      - C.5.7
    na:
      - B
      - B.3
      - B.5
      - B.7
      - B.7.1
      - B.7.2
      - B.7.3
      - B.8

coloring_field: proposed_subclade
