# Everything here is available through the `config` dict in the Snakefile

min_date: "2022-01-01"
regions:
  - "North America"
  - "Europe"
  - "Japan Korea"
  - "Africa"
  - "Western Asia"
  - "Oceania"
  - "South America"
  - "Southern Asia"
  - "South-eastern Asia"

# For parse
fasta_fields:
  - strain
  - virus
  - segment
  - accession
  - date
  - date_submitted
  - region
  - country
  - division
  - location
  - passage_category
  - originating_lab
  - submitting_lab
  - age
  - gender
prettify_fields:
  - region
  - country
  - division
  - location
  - originating_lab
  - submitting_lab
