# Everything here is available through the `config` dict in the Snakefile

min_date: "2021-04-01"
geo_categories: region
frequency_category:
  ha: subclade
  na: clade

nextclade_columns:
  ha:
    - "seqName"
    - "clade"
    - "subclade"
    - "aaSubstitutions"
  na:
    - "seqName"
    - "clade"
    - "aaSubstitutions"

regions:
  - "Africa"
  - "China"
  - "Europe"
  - "Japan Korea"
  - "North America"
  - "Oceania"
  - "South America"
  - "South Asia"
  - "Southeast Asia"
  - "West Asia"

clades_to_plot:
  h1n1pdm:
    ha:
      - "C.1"
      - "C.1.1"
      - "C.1.1.1"
      - "C.1.2"
      - "C.1.3"
      - "C.1.5"
      - "C.1.6"
    na:
      - B.3.1.1
      - B.3.1.2
      - C
      - C.1
      - C.2
      - C.3
      - C.4
      - C.5
      - C.5.1
      - C.5.1.1
      - C.5.2
      - C.5.3
  h3n2:
    ha:
      - "F.1.1"
      - "G.1.1"
      - "G.1.1.2"
      - "G.1.3"
      - "G.1.3.1"
      - "H"
      - "G.1.3.2"
      - "G.2"
      - "G.2.1"
      - "G.2.2"
    na:
      - A.2.2.2
      - B
      - B.1.1
      - B.2
      - B.2.2
      - B.3
      - B.4
  vic:
    ha:
      - "C.1"
      - "C.2"
      - "C.3"
      - "C.4"
      - "C.5"
      - "C.5.1"
      - "C.5.2"
      - "C.5.3"

coloring_field: subclade
auspice_config:
  h1n1pdm: "profiles/flu/auspice_config_h1n1pdm.json"
  h3n2: "profiles/flu/auspice_config_h3n2.json"
  vic: "profiles/flu/auspice_config_vic.json"


fasta_fields:
  - strain
  - virus
  - segment
  - accession
  - date
  - date_submitted
  - region
  - country
  - division
  - location
  - passage_category
  - originating_lab
  - submitting_lab
  - age
  - gender
prettify_fields:
  - region
  - country
  - division
  - location
  - originating_lab
  - submitting_lab
