# Everything here is available through the `config` dict in the Snakefile

min_date: "2021-04-01"
geo_categories: region
frequency_category:
  ha: subclade
  na: clade

nextclade_columns:
  ha:
    - "seqName"
    - "clade"
    - "subclade"
    - "aaSubstitutions"
  na:
    - "seqName"
    - "clade"
    - "aaSubstitutions"

regions:
  - "Africa"
  - "China"
  - "Europe"
  - "Japan Korea"
  - "North America"
  - "Oceania"
  - "South America"
  - "South Asia"
  - "Southeast Asia"
  - "West Asia"

clades_to_plot:
  h1n1pdm:
    ha:
      - C.1
      - C.1.1
      - C.1.7
      - C.1.7.1
      - C.1.7.2
      - C.1.8
      - C.1.9
      - D
      - D.1
      - D.2
      - D.3
      - D.4
    na:
      - C.3
      - C.4
      - C.5
      - C.5.2
      - C.5.3
      - C.5.3.1
      - C.5.3.2
      - C.5.3.3
  h3n2:
    ha:
      - G.1.3.1
      - G.1.3.2
      - J
      - J.1
      - J.2
      - J.3
      - J.4
    na:
      - B.4
      - B.4.1
      - B.4.2
      - B.4.3
  vic:
    ha:
      - C.2
      - C.3
      - C.5
      - C.5.1
      - C.5.4
      - C.5.5
      - C.5.6
      - C.5.7
    na:
      - B
      - B.3
      - B.5
      - B.7
      - B.7.1
      - B.7.2
      - B.7.3
      - B.8

coloring_field: subclade
